# Generated by Django 5.1.4 on 2025-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectmodel_unique_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodemodel',
            name='dwell_time',
            field=models.IntegerField(default=0, help_text='Dwell time in minutes'),
        ),
        migrations.DeleteModel(
            name='QrCodeDwellTimeModel',
        ),
    ]
