# Generated by Django 5.1.4 on 2025-03-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_qrcodemodel_dwell_time_delete_qrcodedwelltimemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdevicemodel',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.projectstagemodel'),
        ),
    ]
