# Generated by Django 5.1.4 on 2025-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectdevicemodel_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstagemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('obs', 'Observation'), ('imp', 'Impression'), ('qr', 'QR Code')], max_length=10, null=True),
        ),
    ]
