# Generated by Django 5.1.4 on 2025-04-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projectstagemodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='dwell_time',
        ),
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='energy_avg',
        ),
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='female_energy_avg',
        ),
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='male_energy_avg',
        ),
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='over_40_energy_avg',
        ),
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='stop_rate',
        ),
        migrations.RemoveField(
            model_name='impressionanalyticsmodel',
            name='under_40_energy_avg',
        ),
        migrations.RemoveField(
            model_name='impressionmodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='projectdevicemodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectdevicemodel',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='projectdevicemodel',
            name='start_date',
        ),
        migrations.AddField(
            model_name='projectdevicemodel',
            name='assignments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdevicemodel',
            name='service',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProjectBoothModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booth_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('operating_hours', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='api.projectmodel')),
            ],
        ),
        migrations.AddField(
            model_name='impressionmodel',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='api.projectboothmodel'),
        ),
        migrations.CreateModel(
            name='UniqueImpressionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('zone', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField()),
                ('impressions_total', models.IntegerField()),
                ('visit_duration', models.FloatField()),
                ('dwell_time', models.FloatField()),
                ('energy_median', models.FloatField()),
                ('face_height_median', models.FloatField()),
                ('biological_sex', models.CharField(max_length=20)),
                ('biological_age', models.CharField(max_length=20)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_impressions', to='api.projectboothmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_impressions', to='api.projectmodel')),
            ],
        ),
    ]
