# Generated by Django 5.1.4 on 2025-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_impressionanalyticsmodel_dwell_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='video_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='video_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
