# Generated by Django 5.1.4 on 2025-05-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sessionmodel_video_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
