# Generated by Django 5.1.4 on 2025-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_projectmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='assigned_project_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
