# Generated by Django 5.1.4 on 2025-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usermodel_assigned_project_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='audio_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
