# Generated by Django 5.1.4 on 2025-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessionmodel_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
