# Generated by Django 5.1.4 on 2025-06-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sessionmodel_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmodel',
            name='transcript',
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='transcripts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
