# Generated by Django 5.1.4 on 2025-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_transcripts_sessionmodel_sentences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='video_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
