# Generated by Django 5.1.4 on 2025-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sessionmodel_video_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITemplateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='HTML', max_length=255, unique=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='video_summary',
        ),
    ]
